name: Update Submodules

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: |
          git submodule update --init --recursive --remote Tweaks/Alderis
          git submodule update --init --recursive --remote Tweaks/DontEatMyContent
          git submodule update --init --recursive --remote Tweaks/iSponsorBlock
          git submodule update --init --recursive --remote Tweaks/protobuf
          git submodule update --init --recursive --remote Tweaks/PSHeader
          git submodule update --init --recursive --remote Tweaks/Return-YouTube-Dislikes
          git submodule update --init --recursive --remote Tweaks/uYouLocalization
          git submodule update --init --recursive --remote Tweaks/YouGroupSettings
          git submodule update --init --recursive --remote Tweaks/YouLoop
          git submodule update --init --recursive --remote Tweaks/YouMute
          git submodule update --init --recursive --remote Tweaks/YouPiP
          git submodule update --init --recursive --remote Tweaks/YouQuality
          git submodule update --init --recursive --remote Tweaks/YouSlider
          git submodule update --init --recursive --remote Tweaks/YouSpeed
          git submodule update --init --recursive --remote Tweaks/YouTimeStamp
          git submodule update --init --recursive --remote Tweaks/YouTubeHeader
          git submodule update --init --recursive --remote Tweaks/YTABConfig
          git submodule update --init --recursive --remote Tweaks/YTClassicVideoQuality
          git submodule update --init --recursive --remote Tweaks/YTHoldForSpeed
          git submodule update --init --recursive --remote Tweaks/YTIcons
          git submodule update --init --recursive --remote Tweaks/YTUHD
          git submodule update --init --recursive --remote Tweaks/YTVideoOverlay
          git submodule update --init --recursive --remote Tweaks/YTweaks
          git submodule update --init --recursive

      - name: Commit & push updated submodule SHAs
        run: |
          if git diff --quiet; then
            echo "No submodule changes to commit."
            exit 0
          fi

          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          git add .
          git commit -m "updated submodules"
          git push

      - name: Show submodule status
        if: always()
        run: git submodule status --recursive
